### ISSUE TITLE
The Workbench commands cannot be found

### ISSUE THREAD

**Issue by aluevano** [Microsoft/vscode-iot-workbench#405] opened 2018-08-28 01:37 UTC
I have managed to create a project (Get Started),
After researching i got the include libraries to be recognized and was able to deploy to the device (MXCHIP). 
What I can't do however is run any other command that is part of the workbench.
For the device or cloud configuration, I always get the "command '<command here>' not found.

I am running the latest release of the VSCode and IoT Workbench (package install).

Is there anything that I need to configure or reinstall?

**Comment by lirenhe** [comment] 2018-08-28 03:40
Usually, the problem is caused by the extension not installed correctly. As i know, this is a VS code issue.
To solve the problem, uninstall IoT workbench extension and delete the cached installation files in C:\Users\{your name}\.vscode\extensions\vsciot-vscode.vscode-iot-workbench-0.1.9. Restart vscode then intall it again.

**Comment by clovett** [comment] 2018-09-17 07:01
or you didn't open vs code with your project.code-workspace.  (open folder doesn't work).

**Comment by lirenhe** [comment] 2018-10-19 03:34
Close it for now. Please let us know if you still face the problem

**Closed** 2018-10-19 03:33 UTC

**Comment by maecky** [comment] 2018-11-21 13:01
I have the same problem:
`command` 'iotworkbench.cloud' not found`

I tried to uninstall the extension and deleted the cache as suggested and it didn't help.
