### ISSUE TITLE
iot workbench 0.1.9 iothub connection failed on macOS

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode-iot-workbench#397] opened 2018-08-17 08:51 UTC
_From @zunhu on August 10, 2018 4:23_

Use command IoT workbench device to connect iothub after push A button and rest, no responding. (Not show connection with iothub successfully).
But it's work on win10.

_Copied from original issue: Microsoft/devkit-sdk#897_

**Comment by lirenhe** [comment] 2018-09-17 04:57
It seems the serial port issue may related to MacOs which means  it would be difficult to solve the problem inside IoT Workbench. To workaround this issue, we need to provide the API  of  bool DevKitMQTTClient_Init(bool hasDeviceTwin = false, bool traceOn = false, const char * connectionString = NULL);   
So user could input the device connection string directly if serial port on Mac does not work.

**Comment by lirenhe** [comment] 2018-11-07 03:49
duplicate of #437

**Closed by lirenhe** 2018-11-07 03:49 UTC
Labels: Duplicate
